version: '3.9'

services:
  csx-app:
    networks:
      - csx-network
    build: .
    container_name: csx-app
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
      - "433:433"

  csx-mysql:
    image: mysql:8.0
    container_name: csx-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Administrador/Documents/Projetos/giovani.devfullstack/private/car_salle_saas/csx/.docker/volumes/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=csx
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev***
      - MYSQL_ROOT_PASSWORD=dev***
    networks:
      - csx-network

networks:
  csx-network:
    driver: bridge
    