version: '3.9'

networks:
  net:
    driver: bridge

services:
  app:
    build: .
    container_name: csx-app
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html    
    networks:
      - net
  
  apache:
    image: httpd:alpine3.14
    container_name: csx-apache
    restart: unless-stopped
    tty: true
    volumes:
      - .docker/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./:/var/www/html
    ports:
      - 8000:80
      - 433:433
    depends_on:
      - app
      - mysql    
    networks:
      - net

  mysql:
    image: mysql:8.0
    container_name: csx-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/volumes/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=csx
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev***
      - MYSQL_ROOT_PASSWORD=dev***
    networks:
      - net
    
